version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - C:\docker-storage:/var/jenkins_home
    networks:
      - jenkinsnet
    restart: unless-stopped

networks:
  jenkinsnet:
